superhero:
  output_path: "dbally_evaluation"
  dataset_path: "data/superhero.json"
  db_name: "superhero"
  view_names: ["SuperheroView", "SuperheroCountByPowerView"]
  difficulty_levels: ["simple"]
