learning_rate: 2e-05
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
num_train_epochs: 2
lr_scheduler_type: "cosine"
logging_steps: 10
bf16: true
fp16: false
gradient_checkpointing: true
logging_strategy: "steps"
max_steps: 10
output_dir: "output"
seed: 42
warmup_steps: 24
save_strategy: "epoch"
save_total_limit: none
do_eval: true
evaluation_strategy: "steps"
eval_steps: 40
per_device_eval_batch_size: 8