# Provide list of test configurations you want to execute
defaults:
  - e2e: [superhero]
  - iql: []
  - text2sql: []

# Attributes common to all tests
model_name: "gpt-3.5-turbo"
neptune:
  log: False
