# Provide list of test configurations you want to execute
defaults:
  - e2e: []
  - iql: [superhero]
  - text2sql: []

llm:
  model_name: "gpt-3.5-turbo"
  api_key: ""

neptune:
  project: "deepsense-ai/db-ally"
  api_token: ""
  log: False
