name: COLLECTION
views: [
  "HeroAttributeView",
  "HeroPowerView",
  "PublisherView",
  "SuperheroView",
]
fallback: "SuperheroFreeformView"

defaults:
  - llm@selector_llm: gpt-3.5-turbo
  - llm@generator_llm: gpt-3.5-turbo
